services:
  magazine-processor:
    container_name: magazine_processor
    image: ghcr.io/vorkosigan76/magazine_processing:latest
    volumes:
      - imports_magazines:/import
      - media_magazines:/processed
      - quarantine_magazines:/quarantine
      - ./config:/app/config
    user: "1000:1000"
    restart: unless-stopped

volumes:
  imports_magazines:
    external: true
  quarantine_magazines:
    external: true
  media_magazines:
    external: true
  