services:
  magazine-processor:
    image: ghcr.io/vorkosigan76/magazine_processing:1.0.0
    build:
      context: https://github.com/Vorkosigan76/magazine_processing.git
    environment:
      - IMPORT_DIR=/import
      - PROCESSED_DIR=/processed
      - QUARANTINE_DIR=/quarantine
    volumes:
      - ./import:/import
      - ./processed:/processed
      - ./quarantine:/quarantine
      - ./config:/app/config
    restart: unless-stopped
